name: fiberchat #changing it will force you to change appname in import statement inside every .dart file.
description: Chats & Calling app

version: 1.1.6+4
publish_to: none

environment:
  sdk: ">=2.19.5 <4.0.0"

dependencies:
  firebase_app_check: ^0.3.1+7
  logger: ^2.5.0
  cloud_functions: ^5.2.0
  audioplayers: ^6.0.0
  pin_input_text_field: ^4.5.1
  audio_session: ^0.1.18
  rxdart: ^0.28.0
  better_open_file: ^3.6.5
  file_saver: ^0.2.11

  url_launcher: ^6.3.1
  circular_countdown_timer: ^0.2.3
  camera: ^0.11.0+2
  oktoast: ^3.4.0
  holding_gesture: ^1.2.0
  flutter_emoji: ^2.5.1
  pip_view: ^0.9.7
  page_transition: ^2.1.0
  wechat_assets_picker: ^9.0.0
  universal_html: ^2.2.4
  image_editor: ^1.3.0
  flutter_image_compress: ^2.1.0
  # mime: ^1.0.5
  video_compress: ^3.1.3
#  link_preview_generator:
#  #1.2.0
  google_mobile_ads: ^5.0.0
  font_awesome_flutter: ^10.7.0
  sms_autofill: ^2.3.1

  firebase_crashlytics: ^4.2.0
  # async: ^2.11.0
  emoji_picker_flutter: ^4.2.0
  flutter_video_info: ^1.3.2
  group_button: ^5.3.4
  flutter_colorpicker: ^1.0.3
  devicelocale: ^0.8.1
  http_auth: ^1.0.4
  cloud_firestore: ^5.5.1
  flutter_cached_pdfview: ^0.4.2
  #firebase_messaging: ^14.7.17
  firebase_messaging: ^15.1.6
  dio: ^5.4.1
  cached_network_image: ^3.3.1

  file_picker: ^8.0.3
  #^5.2.10
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_sound: ^9.6.0
  workmanager: ^0.5.2
  percent_indicator: ^4.2.3
  string_validator: ^1.0.2
  

  intl: ^0.19.0
  connectivity_plus: ^6.0.1
  provider: ^6.1.2
  firebase_auth: ^5.3.4
  html: ^0.15.4
  image_picker: ^1.0.7
  universal_platform: ^1.1.0
  flutter_linkify: ^6.0.0
  dotted_border: ^2.1.0
  diacritic: ^0.1.5

#  image_cropper:
  #^4.0.1
  
  share_plus: ^10.1.4

  scoped_model: ^2.0.0
  local_auth: ^2.3.0
  crypto: ^3.0.3

  
  gal: ^2.3.0
  photo_view: ^0.15.0
  
  overlay_support: ^2.1.0
  jiffy: ^6.2.1
  geolocator: ^13.0.2
  video_player: ^2.8.2

  chewie: ^1.5.0
  media_info: ^0.12.0+2
  #firebase_core: ^2.26.0
  firebase_core: ^3.8.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  agora_rtc_engine: ^6.2.1
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.2.4
  giphy_get: ^3.4.1
#  wakelock:
  #^0.6.2
  cupertino_icons: ^1.0.6
  collection: ^1.18.0
  
  another_flushbar: ^1.12.30
  loader_overlay: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  mailer: ^6.0.1
  optimize_battery: ^0.0.4
  timezone: ^0.10.0
  google_api_availability: ^5.0.0
  nearby_connections: ^4.2.0
  image_gallery_saver: ^2.0.3
  rflutter_alert: ^2.0.7
  flutter_styled_toast: ^2.1.3
  csslib: ^1.0.0



 #not defined
  firebase_storage:
  #^11.6.7
  device_info_plus:
  #^8.2.2
  package_info_plus:
  #^3.1.2
  http: ^1.2.2
  #^1.0.0
  #^0.13.6
  

  #need update
  localstorage: ^4.0.0
  ntp: 2.0.0
  encrypt: 5.0.1


 

  #updated

  flutter_foreground_task: ^8.17.0
  receive_sharing_intent: ^1.8.1
  ffmpeg_kit_flutter: ^6.0.3
  contacts_service: ^0.6.3
  video_editor: ^3.0.0
  flutter_video_thumbnail_plus: ^1.0.5
  
 


  #removed
  # video_thumbnail: 0.5.3
  # dropdown_plus: 0.0.9
  #launch_review: 3.0.1
  #share: 2.0.4
  # random_string: 2.3.1
  # flutter_native_timezone: 2.0.0
    # nfc_manager: ^3.5.0
# flutter_cache_manager: ^3.3.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  flutter_driver:
    sdk: flutter
  test: ^1.16.8

  flutter_launcher_icons: ^0.14.2

flutter_icons:
  # android: "ic_launcher"
  ios: true
  image_path: "assets/appicon/appicon.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - lib/Services/localization/json_languages/
