// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhZWJsfG1kPUmUBss8JvSe2DsDkzvEdnY',
    appId: '1:911276573523:android:541f65d176df68732dd7a6',
    messagingSenderId: '911276573523',
    projectId: 'picxer-25f49',
    databaseURL:
    'https://picxer-25f49-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'picxer-25f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZWJsfG1kPUmUBss8JvSe2DsDkzvEdnY',
    appId: '1:911276573523:ios:ed2a8f4342692f3e2dd7a6',
    messagingSenderId: '911276573523',
    projectId: 'picxer-25f49',
    databaseURL:
    'https://picxer-25f49-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'picxer-25f49.appspot.com',
    iosBundleId: 'org.jhdev.picxer',
  );
}
